Test10
cyberriver/rails_ed pull request #10
Opened 2022-02-26 20:16 UTC by cyberriver

Done

2022-02-27 18:09 UTC, BubuntuClu requested changes

2022-02-27 18:09 UTC, BubuntuClu commented on .byebug_history
> +skip
это в гитигнор надо поместить

2022-02-27 18:09 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  before_action :set_current_path
тебе не надо делать это для каждого экшена, только тогда когда пользователь неавторизован. надо убрать из колбэка и разместить в правильном месте

2022-02-27 18:09 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      if session[:return_link]
`redirect_to session[:return_link] || tests_path` можно так

2022-02-27 18:09 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :authenticate_user!
чтобы не прописывать этот колбэк в каждом контроллере, ты можешь прописать его в родительском

2022-02-27 18:09 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  def index
а что индекс у тестпассажей показывает?

2022-02-27 18:09 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = @user.tests.new(test_params)
это неправильно, ассоциация `tests` отвечает за пройденные тесты, а не за созданные

2022-02-27 18:09 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def set_user
этот метод уже не нужен, у тебя есть метод `current_user`

2022-02-27 18:09 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +  def set_user
дублирование кода `current_user` метода

2022-02-27 18:09 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +      content_tag :p, msg, :id => key, class: "flash #{key}"
стоит еще проверять что есть какой-то текст в этом хэше

2022-02-27 18:09 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_uniqueness_of :email, message: "such email is already busy"
есть стандартная валидация через опцию для `validates`, используй ее вместо старой валидации `validates_uniqueness_of`

2022-02-27 18:09 UTC, BubuntuClu commented on config/routes.rb
> +  #get 'sessions/new'
удалый ненужный код, не надо его комментировать и тащить в репу

2022-02-27 18:09 UTC, BubuntuClu commented on db/migrate/20220222080410_add_password_digest_to_users.rb
> +class AddPasswordDigestToUsers < ActiveRecord::Migration[7.0]
ты забыл добавить файл `schema.rb`. миграция должна была поменять его описание

2022-02-27 18:09 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_uniqueness_of :email, message: "such email is already busy"
убедись что в БД создан уникальный индекс на поле почты

2022-03-04 19:34 UTC, cyberriver commented on .byebug_history
> +skip
done

2022-03-04 19:39 UTC, cyberriver commented on app/controllers/application_controller.rb
> +  before_action :set_current_path
точно, хорошая мысль. Перенес

2022-03-04 19:41 UTC, cyberriver commented on app/controllers/sessions_controller.rb
> +      if session[:return_link]
оо красиво, не знал, что так можно

2022-03-04 20:00 UTC, cyberriver commented on app/controllers/test_passages_controller.rb
> +  before_action :authenticate_user!
Done

2022-03-04 20:03 UTC, cyberriver commented on app/controllers/test_passages_controller.rb
> +  def index
Запускает рендер индекс вью, чтобы показать все тестпассажи авторизованного пользователя, оч удобно

2022-03-04 21:37 UTC, cyberriver commented on app/controllers/users_controller.rb
> +  def set_user
да точно)... .убрал

2022-03-04 22:00 UTC, cyberriver commented on app/helpers/application_helper.rb
> +      content_tag :p, msg, :id => key, class: "flash #{key}"
добавил проверку.

2022-03-04 22:01 UTC, cyberriver commented on config/routes.rb
> +  #get 'sessions/new'
удалил

2022-03-04 22:01 UTC, cyberriver commented on db/migrate/20220222080410_add_password_digest_to_users.rb
> +class AddPasswordDigestToUsers < ActiveRecord::Migration[7.0]
окк

2022-03-04 22:27 UTC, cyberriver commented on app/models/user.rb
> +  validates_uniqueness_of :email, message: "such email is already busy"
done

2022-03-05 07:26 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +  before_action :current_user, only: %i[show edit update]
нет, так не надо делать. нужно вызывать метод, там где тебе нужно, а не перед экшенами и вызывать потом переменную.

2022-03-05 07:26 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +    @current_user=User.new
лучше тут везде оставить user

2022-03-05 07:26 UTC, BubuntuClu commented on app/views/users/_form.html.erb
> +<%= form_with model: @current_user, local: true do |form| %>
оставь `user` везде. ты можешь устроить конфликт текущего пользователя и пользователя которого обнловляешь

2022-03-05 07:27 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  def index
а для чего это вообще нужно?

2022-03-05 07:27 UTC, BubuntuClu requested changes

2022-03-05 07:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = @user.tests.new(test_params)
не поправил

2022-03-05 07:27 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
>    def set_user
не поправил

2022-03-05 08:15 UTC, cyberriver commented on app/controllers/users_controller.rb
> +    @current_user=User.new
добавил

2022-03-05 08:18 UTC, cyberriver commented on app/views/users/_form.html.erb
> +<%= form_with model: @current_user, local: true do |form| %>
Готово

2022-03-05 08:43 UTC, cyberriver commented on app/controllers/tests_controller.rb
> +    @test = @user.tests.new(test_params)
поправил

2022-03-06 17:42 UTC, BubuntuClu requested changes

2022-03-06 17:42 UTC, BubuntuClu commented on .byebug_history
> +help
тут ничего не изменилось, файл все еще в ПРе

2022-03-06 17:42 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +  before_action :current_user
не надо вызывать этот метод в колбэках. вызываешь этот методя прямо в коде, там, где тебе нужен пользователь текущий

2022-03-06 17:42 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  before_action :current_user, only: %i[create new start]
и тут тоже, надо удалить этот колбэк и использовать в методах метод current_user

2022-03-06 17:42 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test= @user.author_tests.new
обращаться к пользователю надо через метод(это вроде тебе уже описывал)

2022-03-06 17:42 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = @user.tests.new(test_params)
поправил неправильно. надо использовать ассоциацию созданных тестов. ты используешь тесты прохождений

2022-03-06 17:42 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +  before_action :current_user, only: %i[show edit update]
это надо поправить

2022-03-06 17:42 UTC, BubuntuClu commented on app/models/user/auth.rb
> +    validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
отсюда стоит убрать проверку почты, так как она есть в проверке пользователя

2022-03-06 17:42 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +    @user ||= User.find_by(id: session[:user_id]) if session[:user_id]
обычно переменная для мемоизации называется так же как и метод. стоит придерживаться этого стиля написания кода

2022-03-06 19:20 UTC, cyberriver commented on .byebug_history
> +help
понял, удалил файл и заново перезалил. Сейчас еще раз добавлю в гитигнор

2022-03-06 19:20 UTC, cyberriver commented on app/controllers/test_passages_controller.rb
> +  before_action :current_user
убралл

2022-03-06 19:20 UTC, cyberriver commented on app/controllers/tests_controller.rb
> +  before_action :current_user, only: %i[create new start]
готово

2022-03-06 19:21 UTC, cyberriver commented on app/controllers/tests_controller.rb
> +    @test= @user.author_tests.new
понял

2022-03-07 16:11 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +    @current_user=User.new
тут верни user переменную, так как ты можешь перетереть значение current_user

2022-03-07 16:11 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +    @current_user=User.new
[BubuntuClu](https://github.com/BubuntuClu) [2 days ago](https://github.com/cyberriver/rails_ed/pull/10/commits/d9792059374de471db85acc3d0cd5926853e37a7#r820060751) 
лучше тут везде оставить user

2022-03-12 13:50 UTC, merged