Test14
cyberriver/rails_ed pull request #14
Opened 2022-04-22 04:14 UTC by cyberriver

2022-04-30 16:07 UTC, BubuntuClu requested changes

2022-04-30 16:07 UTC, BubuntuClu commented on app/controllers/admin/gists_controller.rb
> +  before_action :set_gists, only: %i[index]
зачем куча лишних строк вместо? не надо просто так плодить колбэки

```
def index
   @gists = Gist.all
end
```

2022-04-30 16:07 UTC, BubuntuClu commented on app/controllers/admin/users_controller.rb
> +  before_action :set_users, only: %i[index]
аналогично и тут

2022-04-30 16:07 UTC, BubuntuClu commented on app/controllers/test_passages_controller.rb
> +    if conn.response.status.in?(200..299)
вынеси эту проверку в сервис. при замене клиента проверка может быть другой, поэтому не надо реализацию выносить из сервиса

2022-04-30 16:07 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    @response  = @client.http_client.last_response
не уверен что `call` должен отдавать эту строку. пусть отдает `@client.http_client.create_gist(gist_params)` и там будет ссылка нужная. а проверку `last_response` сделаешь в методе `success?`. снаружи сервиса `last_response` вроде не нужОн

2022-04-30 16:07 UTC, BubuntuClu commented on config/routes.rb
> +      post :gist
resource gists only?

2022-04-30 16:07 UTC, BubuntuClu commented on db/migrate/20220427203218_create_gists.rb
> +      t.string :email
сделай тут референс к пользователю

2022-04-30 16:07 UTC, BubuntuClu commented on app/models/user.rb
> +  has_many :gists_email, class_name: :Gist, foreign_key: :email
оч странное решение. а почему так, а не через id?

наименование ассоциации говорит что ты хочешьполучить почту из гистов? а зачем это нужно делать?

2022-04-30 16:07 UTC, BubuntuClu commented on lib/clients/git_hub_client.rb
> +     @http_client = Octokit::Client.new(:access_token => ACCESS_TOKEN)
используй новый синтаксис задания параметров, хэш-рокет старайся устранять

2022-04-30 16:07 UTC, BubuntuClu commented on lib/clients/git_hub_client.rb
> +class GitHubClient
вообще этот класс тебе не нужен. ты можешь в сервисе сразу устанавливать `Octokit::Client`

2022-05-01 10:31 UTC, cyberriver commented on app/controllers/admin/gists_controller.rb
> +  before_action :set_gists, only: %i[index]
поправил

2022-05-01 10:31 UTC, cyberriver commented on app/controllers/admin/users_controller.rb
> +  before_action :set_users, only: %i[index]
поправил

2022-05-01 10:36 UTC, cyberriver commented on app/services/gist_question_service.rb
> +    @response  = @client.http_client.last_response
response сам оставил, просто из него берутся данные, метод data, для сохранения данных из json в базу. это просто удобно. 

      gist_save(@test_passage.current_question,
                      conn.response.data.html_url,
                      @test_passage.user.email)

2022-05-01 17:42 UTC, cyberriver commented on app/models/user.rb
> +  has_many :gists_email, class_name: :Gist, foreign_key: :email
переделал), неправитльно прочитал задание, мне сначала показалось, что нужно пользователя искать через email

2022-05-01 17:42 UTC, cyberriver commented on config/routes.rb
> +      post :gist
готово).. добавил ресурсы, новый контроллер и все перенес туда)

2022-05-01 17:42 UTC, cyberriver commented on db/migrate/20220427203218_create_gists.rb
> +      t.string :email
готово

2022-05-01 17:44 UTC, cyberriver commented on lib/clients/git_hub_client.rb
> +     @http_client = Octokit::Client.new(:access_token => ACCESS_TOKEN)
done

2022-05-01 17:51 UTC, cyberriver commented on lib/clients/git_hub_client.rb
> +class GitHubClient
кстати да:). спс. убрал его

2022-05-01 18:25 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    if @client.last_response.status.in?(200..299)
само выражение `@client.last_response.status.in?(200..299)` и так вернет true/false, не нужно руками прописывать это

2022-05-01 18:25 UTC, BubuntuClu commented on app/services/gist_question_service.rb
> +    @response  = @client.last_response
эта строка тут не нужна

2022-05-01 18:25 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    conn.call
`result = conn.call` чтобы сохранить данные создания сервиса

2022-05-01 18:25 UTC, BubuntuClu commented on app/controllers/gists_controller.rb
> +    conn = GistQuestionService.new(@test_passage.current_question)
что такое `conn`?

2022-05-01 18:25 UTC, BubuntuClu commented on config/routes.rb
> +    # post :gist
ненужный код удаляй, зачем его хранить?

2022-05-02 07:06 UTC, cyberriver commented on app/services/gist_question_service.rb
> +    if @client.last_response.status.in?(200..299)
поправил

2022-05-02 07:14 UTC, cyberriver commented on app/services/gist_question_service.rb
> +    @response  = @client.last_response
done

2022-05-02 07:16 UTC, cyberriver commented on app/controllers/gists_controller.rb
> +    conn = GistQuestionService.new(@test_passage.current_question)
conn = это клиент, заменил на client

2022-05-02 07:17 UTC, cyberriver commented on config/routes.rb
> +    # post :gist
done

2022-05-02 07:17 UTC, merged