Test18
cyberriver/rails_ed pull request #21
Opened 2022-07-12 20:20 UTC by cyberriver

2022-08-15 07:28 UTC, BubuntuClu requested changes

2022-08-15 07:28 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    (test.timer - (Time.now - created_at)).to_i <= 0
(test.timer - (Time.now - created_at)).to_i этот кусок кода повторяется в обоих методах

2022-08-15 07:28 UTC, BubuntuClu commented on app/services/check_achivements_service.rb
> +    category = Category.find_by(title: category_name)
ты знаешь `join`запросы, используй их. и у тебя есть метод в тестах - найти тесты по имени категории

2022-08-15 07:28 UTC, BubuntuClu commented on app/services/check_achivements_service.rb
> +    @test_passages_count > count.to_i
слишком легкий бадж. реализуй "прохождение с первого раза"

2022-08-18 21:13 UTC, cyberriver commented on app/services/check_achivements_service.rb
> +    category = Category.find_by(title: category_name)
кстати да, спс что обратил внимание, я не подумал об этом. поправил

2022-08-18 21:17 UTC, cyberriver commented on app/models/test_passage.rb
> +    (test.timer - (Time.now - created_at)).to_i <= 0
убрал код с таймером вообще:). будет в отдельном ПР

2022-08-18 21:17 UTC, cyberriver commented on app/services/check_achivements_service.rb
> +    @test_passages_count > count.to_i
добавил новый бейдж

2022-08-19 07:10 UTC, BubuntuClu commented on app/services/check_achivements_service.rb
> +        if send(rule, badge.parameter)
`@user.badges.push(badge) if send(rule, badge.parameter)` давай хотя бы так, чтоб лестница из `if` была не столь очевидной

2022-08-19 08:07 UTC, cyberriver commented on app/services/check_achivements_service.rb
> +        if send(rule, badge.parameter)
done

2022-08-19 08:07 UTC, merged