first part of home work
cyberriver/rails_ed pull request #7
Opened 2022-01-31 07:09 UTC by cyberriver

2022-02-01 06:54 UTC, BubuntuClu requested changes

2022-02-01 06:54 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +require 'byebug'
так лучше не делать. у кого-то может не стоять гем в гемсете и тогда будет ошибка. у тебя есть гемфайл, вноси туда все гемы которые ты ставишь для приложения

2022-02-01 06:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.all
нужно показывать только все вопросы определенного теста

2022-02-01 06:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.create(question_params)
для создания вопроса требуется тест. используй ассоциации чтобы создать вопрос. так же параметры с фронта могут быть не валидные и вопрос не будет создан, это надо учитывать и оповещать пользователя

2022-02-01 06:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.destroy!
бэнг метод при ошибки выдаст исключение. надо обрабатывать его через `rescue`, либо не использовать бэнг метод(он тут не оправдан)

2022-02-01 06:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.update!(body: params[:question][:body])
бэнг метод при ошибки выдаст исключение. надо обрабатывать его через `rescue`, либо не использовать бэнг метод(он тут не оправдан)

2022-02-01 06:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.update!(body: params[:question][:body])
у тебя есть метод `question_params`, зачем руками собираешь параметры которые надо обновить?

2022-02-01 06:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.permit(:body, :test_id)
параметр `test_id` будет подставляться через ассоциацию, когда переделаешь на нее. отсюда надо убрать этот параметр

2022-02-01 06:54 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @form_auth_token = form_authenticity_token
а это зачем?

2022-02-01 06:54 UTC, BubuntuClu commented on app/models/question.rb
> +  #validates :body, presence:true
почему валидацию отключил? она все еще нужна

2022-02-01 06:54 UTC, BubuntuClu commented on app/views/questions/index.html.erb
> +      <td><%= button_to "Delete", question_path(q.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %></td>
рекомендую поставить версию рельсы ниже. странное ограничение для `link_to` с `method`

2022-02-01 06:54 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form class="" action="/questions?test_id=1" method="post">
у тебя может не быть теста с таким ID, нельзя хардкодить ID. через параметр получай ID теста.

и вообще ресурс вопросов должен быть вложен в ресурс тестов. у тебя ведь по структуре БД вопрос зависит от теста

2022-02-01 06:54 UTC, BubuntuClu commented on config/routes.rb
> +  resources :questions do
вложенность должна быть сделана наоборот

2022-02-01 06:54 UTC, BubuntuClu commented on config/routes.rb
> + #root to: 'questions#index'
весь ненужный код сразу удаляй, не стоит захламлять репозиторий

2022-02-01 11:39 UTC, cyberriver commented on app/controllers/application_controller.rb
> +require 'byebug'
поправил

2022-02-01 22:33 UTC, cyberriver commented on app/views/questions/index.html.erb
> +      <td><%= button_to "Delete", question_path(q.id), method: :delete, class: "btn btn-danger", data: { confirm: "Are you sure?" } %></td>
ну я на этой останусь, интеерсно.

2022-02-01 22:34 UTC, cyberriver commented on app/views/questions/new.html.erb
> +<form class="" action="/questions?test_id=1" method="post">
переделал

2022-02-01 22:34 UTC, cyberriver commented on config/routes.rb
> +  resources :questions do
исправил

2022-02-01 22:34 UTC, cyberriver commented on config/routes.rb
> + #root to: 'questions#index'
убрал

2022-02-01 22:34 UTC, cyberriver commented on app/controllers/questions_controller.rb
> +    @question.update!(body: params[:question][:body])
готово)

2022-02-01 22:34 UTC, cyberriver commented on app/controllers/questions_controller.rb
> +    @question.destroy!
поправил

2022-02-01 22:34 UTC, cyberriver commented on app/controllers/questions_controller.rb
> +    @question = Question.create(question_params)
исправил

2022-02-01 22:35 UTC, cyberriver commented on app/controllers/questions_controller.rb
> +    @question = Question.all
исправил

2022-02-02 07:18 UTC, BubuntuClu requested changes

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.create(question_params)
ассоциация все еще не используется. так же нет проверки был ли вопрос сохранен

```
question = @test.questions.new(questions_params)
if question.save
  Render good
else
  Render bad
end
```

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  def find_test
тут что-то случилось с кодом, какая-то мешанина.
нахождение теста это тоже приватный метод

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    redirect_to test_questions_path(session[:test_id])
почему тест береться из сессии, а не из параметров?

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    params.require(:question).permit(:body, :test_id)
параметр теста не убрал

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @form_auth_token = form_authenticity_token
?

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.where(test_id: params[:test_id])
находи вопросы через ассоциацию теста

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  after_action :send_log_message
отладочные методы можно убрать, в проде они не нужны

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_question, only: %i[show edit update destroy]
находить вопрос можно через колбэк

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.create(test_params)
нет проверки на сохраненность теста

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test.assign_attributes(test_params)
есть метод `update`которые возрвщает `true/false` чтобы можно было определить прошло ли сохранение

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @form_auth_token = form_authenticity_token
и тут тоже этот код. это фишка у 7ки?

2022-02-02 07:18 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    params.require(:test).permit([:title, :level, :category_id, :author_id] )
почему параметры в массиве?

2022-02-02 07:18 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +<form class="" action="/tests/:test_id/questions" method="post">
тут нужна интерполяций, чтобы путь определился правильно

2022-02-02 07:18 UTC, BubuntuClu commented on app/views/questions/new.html.erb
> +      <input type="text" name="question[test_id]" id="question-test_id" value = <%= session[:test_id] %>>
тест не надо выбирать, он должен определяться через путь.
почему из сессии берешь тест, а не из параметров?

2022-02-02 10:52 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :find_question, only: %i[show edit update destroy]
тест*

2022-02-02 17:46 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  after_action :send_log_message
это тоже можно грохнуть

2022-02-02 17:46 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question.update(question_params)
по-хорошему это тоже оборачивать в `if` надо

2022-02-02 17:46 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +       redirect_to test_questions_path(@test.id)
можно просто `test_questions_path(@test)` без указания поля. рельса умная, поймет

2022-02-02 17:46 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    render json: {question: @test}
кек, копипаста зло

2022-02-02 17:46 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +    @test = Test.create(test_params)
`create` под копотом вызывает сохранение в БД. так что сейчас генерируется два одинаковых запроса в БД от `create` и от `save`. надо заменить `create` на `new`

2022-02-02 18:16 UTC, cyberriver commented
все замечания поправилы

2022-02-02 18:16 UTC, merged