Test8
cyberriver/rails_ed pull request #8
Opened 2022-02-09 21:36 UTC by cyberriver

Done

2022-02-10 06:44 UTC, BubuntuClu requested changes

2022-02-10 06:44 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>      if @question.save
ветку для неудачи надо поправить. ты уже имеешь вьюхи, отдать просто текст уже не подходит

2022-02-10 06:44 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>         render plain: 'что-то пошло не так в момент сохранения'
надо поправить отдачи при неуспехе

2022-02-10 06:44 UTC, BubuntuClu commented on app/helpers/application_helper.rb
> +    out = "https://github.com/#{author}/#{repo}"
формируй тут хэлпер `link_to`, сейчас метод выглядит странно, ты просто передаешь две строки, чтобы их сложить.

зачем тут нужна переменная `out`? что она делает?

2022-02-10 06:44 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    if params[:action] == "new"
отталкивайся от состояния вопроса `new_record?/persisted?` а не от названия метода

2022-02-10 06:44 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    elsif params[:action] == "edit"
`elsif` плохая конструкция, которая свидетельствует скорее всего об плохой архитектуре кода, лучше ее не использовать.

тебе тут не нужна переманная дополнительная, чтобы отдать ответ. верни отсюда правильну строку, а уже вокруг результата делай разметку

2022-02-10 06:44 UTC, BubuntuClu commented on app/helpers/session_helper.rb
> +module SessionHelper
это удали. будем делать это другим способом

2022-02-10 18:52 UTC, cyberriver commented on app/controllers/questions_controller.rb
>      if @question.save
done

2022-02-10 18:52 UTC, cyberriver commented on app/controllers/questions_controller.rb
>         render plain: 'что-то пошло не так в момент сохранения'
done

2022-02-10 18:58 UTC, cyberriver commented on app/helpers/application_helper.rb
> +    out = "https://github.com/#{author}/#{repo}"
done

2022-02-10 19:09 UTC, cyberriver commented on app/helpers/questions_helper.rb
> +    if params[:action] == "new"
done

2022-02-10 19:10 UTC, cyberriver commented on app/helpers/questions_helper.rb
> +    elsif params[:action] == "edit"
понял, переделал

2022-02-10 19:41 UTC, cyberriver commented on app/helpers/session_helper.rb
> +module SessionHelper
done

2022-02-11 06:15 UTC, BubuntuClu commented on app/controllers/application_controller.rb
> +  include SessionHelper
это подклчюение тоже надо грохнуть

2022-02-11 06:15 UTC, BubuntuClu commented on app/helpers/questions_helper.rb
> +    out = ''
зачем тебе тут эта переменная?
почему просто строку не отдать? зачем массив

2022-02-11 08:32 UTC, cyberriver commented on app/controllers/application_controller.rb
> +  include SessionHelper
грохнул

2022-02-11 08:32 UTC, cyberriver commented on app/helpers/questions_helper.rb
> +    out = ''
грохнул

2022-02-15 15:48 UTC, merged