9th Homework
cyberriver/rails_ed pull request #9
Opened 2022-02-17 10:42 UTC by cyberriver

2022-02-20 16:56 UTC, BubuntuClu requested changes

2022-02-20 16:56 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +      logger.info("PARAMS FIND ANSWER  [#{params}] ")
отладочную инфу не стоит допускать в прод. пока локально разрабатываешь можешь дебажить логами, но в прод это не должно попадать

2022-02-20 16:56 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +      logger.info("PARAMS FIND ANSWER  [#{@answer}] ")
не забывай что результат последней строки ретурнится из методов, иногда это может приводить к неожиданным последствиям

2022-02-20 16:56 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  after_action :push_to_log
тоже самое про логи

2022-02-20 16:56 UTC, BubuntuClu commented on app/controllers/tests_controller.rb
> +  def push_to_log
а зачем ты это логируешь? подобные данные рельсовый сервер сам логирует и это видно в консоле

2022-02-20 16:56 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +  def test_result(test_passage)
это метож модели

2022-02-20 16:56 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    if result > 0.85
это сравнение тоже можно сделать через метод модели - `test_passage.success?`.
тогда и магическое число можно будет исправить. почему 85? без контекста не понятно. помести в константу в модели и обзови понятно

2022-02-20 16:56 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.touch
Сделайте назначение следующего вопроса в модели TestPassage с помощью обратного вызова - ты по сути не сделал задание, все равно "руками" дергаешь вызов, просто через колбэк, который ты сам триггеришь. объедини установку след вопроса с установкой первого вопроса, чтобы метод был всего один

2022-02-20 16:56 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    save!
сначала сохраняешь объект в `accept!`, потом в этом методе. много сохранений

2022-02-20 16:56 UTC, BubuntuClu commented on config/routes.rb
> +    resources :questions, shallow: true, expect: :index do
https://github.com/cyberriver/rails_ed/pull/9/files#diff-4030ed952f1bc9a865520f7dc26bd80426075452cf8de9c65ebbfe549acf8cc1R8
в роутах исключил метода, а в контроллере оставил

2022-02-20 16:56 UTC, BubuntuClu commented on config/routes.rb
> +  resources :answers
дублирование ресурса

2022-02-20 16:56 UTC, BubuntuClu commented on db/migrate/20220216171355_drop_table_tests_users.rb
> +  def up
если есть метод `up`, то должен быть и метод `down`, чтобы при откатывании миграции не словить ошибку.
в данном случае, метод `down` можно оставить пустым

2022-02-21 18:33 UTC, cyberriver commented on app/controllers/answers_controller.rb
> +      logger.info("PARAMS FIND ANSWER  [#{params}] ")
готово, убрал.

2022-02-21 18:38 UTC, cyberriver commented on app/controllers/answers_controller.rb
> +      logger.info("PARAMS FIND ANSWER  [#{@answer}] ")
понял

2022-02-21 18:39 UTC, cyberriver commented on app/controllers/tests_controller.rb
> +  after_action :push_to_log
убрал

2022-02-21 18:39 UTC, cyberriver commented on app/controllers/tests_controller.rb
> +  def push_to_log
да это я просто отладку делал

2022-02-21 18:45 UTC, cyberriver commented on app/helpers/test_passages_helper.rb
> +  def test_result(test_passage)
перенес в модель

2022-02-21 18:45 UTC, cyberriver commented on app/models/test_passage.rb
> +    self.touch
готово). разобрался

2022-02-21 18:45 UTC, cyberriver commented on app/models/test_passage.rb
> +    save!
поправил

2022-02-21 18:46 UTC, cyberriver commented on config/routes.rb
> +    resources :questions, shallow: true, expect: :index do
поправил, косяк

2022-02-21 19:47 UTC, cyberriver commented on db/migrate/20220216171355_drop_table_tests_users.rb
> +  def up
Done

2022-02-21 19:47 UTC, cyberriver commented on config/routes.rb
> +  resources :answers
убрал

2022-02-22 06:58 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    if result > 0.85
это не поправил

2022-02-22 08:01 UTC, merged